name: CI
#
on: [push]
#
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      #- name: Test
      #  uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
      #  with:
      #    arguments: test
      - name: Build JAR archive dev
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: |
            buildDev -Penv=dev
             
      - name: Build JAR archive prod
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: |
            buildProd

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs